idsthings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
urlpatterns = [
    #path('polls/', include('polls.urls')),
    path('', include('tracken.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tracken/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'tracken'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('progress/', views.progressTracker, name='progress'),
    path('new-entry/<int:year>/', views.NewEntryView.as_view(), name='new-entry'),
    path('entry/<int:pk>/', views.EntryView.as_view(), name='entry'),
    path('edit-goal/<int:pk>', views.EditGoalView.as_view(), name='edit-goal')
    #path('login/', auth_views.LoginView.as_view(template_name='tracken/login.html'), name='login'),
    #path('password-reset', auth_views.PasswordResetView.as_view(), name='password_reset')
    #path('<int:question_id>/', views.detail, name='detail'),
    #path('<int:question_id>/results/', views.results, name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

tracken/models.py
from django.db import models
from django.contrib.auth.models import User
from vote.models import VoteModel
from django.urls import reverse
import datetime

# Create your models here.

class Year (models.Model):
    year = models.PositiveIntegerField()
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    hours_goal = models.PositiveSmallIntegerField(verbose_name='Goal for hours to accomplish', default=120)
    def __str__(self):
        return self.student.username + ' ' + str(self.year)
    
    def get_absolute_url(self):
        return reverse('tracken:progress')

class Entry (models.Model):
    work_date = models.DateTimeField('Time work happened', auto_now_add=True)
    #updated_date = models.DateTimeField(auto_now=True)
    time_spent = models.DurationField('Time spent on IDS', default=datetime.timedelta(hours=1))
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    goal = models.TextField(verbose_name='Goals for work period', null=True, blank=True)
    accomplishments = models.TextField(verbose_name='Work accomplished', default='Something, anyways')

    def get_absolute_url(self):
        return reverse('tracken:entry', kwargs={"pk": self.id})

    def __str__(self):
        return self.accomplishments

class Comment (VoteModel, models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Thoughts on entry', max_length=50000)

tracken/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, get_user
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic
from django.db.models import Sum, Count

from .models import User, Year, Entry, Comment
import datetime

# Create your views here.

class HomeView(generic.TemplateView):
    template_name = 'tracken/home.html'

class AboutView(generic.TemplateView):
    template_name = 'tracken/about.html'

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            year = Year(student=user, year=datetime.datetime.today().year)
            year.save()
            login(request, user)
            return redirect('tracken:home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required(redirect_field_name='tracken:progress')
def progressTracker(request):
    year = get_object_or_404(Year, student=get_user(request))
    entryList = year.entry_set.order_by('work_date')
    if entryList.count():
        hours = entryList.aggregate(Sum('time_spent'))['time_spent__sum'].total_seconds() / 3600
    else:
        hours = 0
    context = {
        'entry_list': entryList,
        'year': year.id,
        'hours_spent': hours,
        'hours_goal': year.hours_goal,
    }
    return render(request, 'tracken/progress.html', context)

class NewEntryView(generic.CreateView, LoginRequiredMixin):
    model = Entry
    template_name = 'tracken/new-entry.html'
    fields = ['time_spent', 'goal', 'accomplishments']
    def form_valid(self, form):
        year = get_object_or_404(Year, pk=self.kwargs['year'])
        form.instance.year = year
        return super(NewEntryView, self).form_valid(form)

class EntryView(generic.DetailView, LoginRequiredMixin):
    model = Entry
    template_name = 'tracken/entry.html'

class EditGoalView(generic.UpdateView, LoginRequiredMixin):
    model = Year
    template_name = 'tracken/edit-goal.html'
    fields = ['hours_goal']

tracken/templates/tracken/about.html
{% extends 'tracken/base.html' %}

{% block title %}About{% endblock %}

{% block header %}
<h1>About Tracken</h1>
{% endblock %}

{% block content %}
<p>
    <b>Tracken is a simple IDS tracking system designed to demonstrate relational databases.</b>
</p>
<div class="smallish separated">
    <p class="spaced">
        <b>Tables</b> are the most important elements of nearly any database.
        Let's take a look at an example one used for IDS.
    </p>
    <br>
    <code class="smallish">
        <table class="bordered">
            <thead>
                <tr>
                    <th>Primary Key</th>
                    <th>Time work happened</th>
                    <th>Time spent</th>
                    <th>Goals</th>
                    <th>Accomplishments</th>
                    <th>Project Foreign Key</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>574</td>
                    <td>Thursday 4:30 pm</td>
                    <td>2 hours</td>
                    <td><q>Get stuff done</q></td>
                    <td><q>Got stuff done</q></td>
                    <td>38</td>
                </tr>
                <tr>
                    <td>575</td>
                    <td>Friday 8:00 pm</td>
                    <td>2 hours, 30 mins</td>
                    <td><q>Do something</q></td>
                    <td><q>Something</q></td>
                    <td>25</td>
                </tr>
                <tr>
                    <td>576</td>
                    <td>Saturday 11:00 am</td>
                    <td>45 mins</td>
                    <td><q>Get stuff done</q></td>
                    <td><q>Got stuff done</q></td>
                    <td>62</td>
                </tr>
                <tr>
                    <td>577</td>
                    <td>Saturday 1:00 pm</td>
                    <td>1 hour, 50 mins</td>
                    <td><q>Get stuff done</q></td>
                    <td><q>Got stuff done</q></td>
                    <td>47</td>
                </tr>
            </tbody>
        </table>
    </code>
    <p>
        As you can see, the rows in this table represent entrires in a logbook.
        However, there are still some columns in this table that don't seem to be relevant.
        Specifically, the <q><b>Primary Key</b></q> and <q><b>Project Foreign Key</b></q> rows.
    </p>
    <p>
        The first row that you see in the table isn't an entry, but rather a definition of what the columns are.
        These are called attributes.
        All rows must conform with these attributes, nothing more and nothing less -
        although null and blank values can be accepted, but that depends on the configuration.
    </p>
    <p>
        These are more or less specific to a type of database managemant system called RDBMS,
        with the <q>R</q> standing for relational.
        They're named this way because the tables are connected with a relational model.
    </p>
    <br>
    <p>
        The primary key is used as a unique identifier for each row in the database -
        or tuple, in RDBMS terms. It's almost always a number.
        However, you'll almost never see the primary key from an actual website or application.
        The last <q>foreign key</q> column, though,
        refers to a <b>different table's</b> primary key.
    </p>
    <p>
        This is where the relations in RDBMSs begin.
        Every foreign key in a column will be the primary key of another table.
        This table table would be filled with IDS projects. Here's an example:
    </p>
    <br>
    <code class="smallish">
        <table class="bordered">
            <thead>
                <tr>
                    <th>Primary Key</th>
                    <th>Year</th>
                    <th>Topic</th>
                    <th>Hours goal</th>
                    <th>Student Foreign Key</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>47</td>
                    <td>2019</td>
                    <td><q>Video games and violence</q></td>
                    <td>120</td>
                    <td>37</td>
                </tr>
                <tr>
                    <td>48</td>
                    <td>2019</td>
                    <td><q>Ancient architecture</q></td>
                    <td>160</td>
                    <td>21</td>
                </tr>
                <tr>
                    <td>49</td>
                    <td>2019</td>
                    <td><q>Triangles</q></td>
                    <td>120</td>
                    <td>34</td>
                </tr>
            </tbody>
        </table>
    </code>
    <p>
        This table has another foreign key to a table called students,
        but I'm sure you can figure out what would be in that table.
        Another thing that you might have noticed is that although there is a column
        for the goal of hours, but there isn't a field for the amount of hours
        because that would be a violation of <b>database normalization</b>.
    </p>
    <p>
        Database normalization is a technique which organizes tables
        to make them less redundant and unnecessarily dependent on
        illogical data. These are divided into several rules called
        <b>normal forms</b>.
    </p>
    <ul>
        <li>
            The first normal form requires that each cell contains only a single value,
            and that each row/tuple needs to be unique.
        </li>
        <li>
            The second normal form requires the first normal form to be followed,
            adding a constraint that limits primary keys to one column.
        </li>
        <li>
            The third normal form requires the second normal form, but also
            requires an absence of <b>transitive functional dependencies</b>.
            Transitive functional dependencies are when changing one non-key
            column could cause a different non-key column to change.
        </li>
        <li>
            There are many more normal forms,
            but these three are by far the most important.
        </li>
    </ul>
    <h2 class="spaced">SQL</h2>
    <p>
        You might be wondering how these databases are actually interacted with.
        <b>Structured Query Language</b> is a language used for
        managing the data in relational database. SQL is usually executed in single commands,
        which can either:
    </p>
    <ul>
        <b>
            <li>create,</li>
            <li>retrieve,</li>
            <li>update,</li>
            <li>or manage</li>
        </b>
    </ul>
    <p>
        data.
    </p>
    <p>
        But this still doesn't answer the question of
        how database data 
    </p>
    <p>
        There are many different types of databases. These can include:
    </p>
    <ul>
        <li>
            <b>Hierarchical databases</b>, which are basically a tree of tables.
        </li>
    </ul>
</div>
{% endblock %}

tracken/templates/tracken/base.html
{% load nav_active %}
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %} {% endblock %} | Tracken</title>
        <link rel="shortcut icon" type="image/x-icon" href="{%  static 'tracken/favicon.ico' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'tracken/style.css' %}">
        {% fontawesome_5_static %}
        <script type="text/javascript">
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <header>
            <nav class="topnav" id="myTopnav">
                <a href="{% url 'tracken:home' %}">Home</a>
                {% if not user.is_anonymous %}
                    <a href="{% url 'tracken:progress' %}">Your progress</a>
                {% endif %}
                <a href="{% url 'tracken:about' %}">About</a>
                {% if user.is_anonymous %}
                <a href="{% url 'tracken:signup' %}" class="right">Make an account</a>
                <a href="{% url 'tracken:login' %}" class="right">Log In</a>
                {% else %}
                <a href="{% url 'tracken:logout' %}" class="right">Logout of {{ user.username }}</a>
                {% endif %}
                <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
                </a>
            </nav>
            <div class="header">
                {% block header %}
                <h2>Tracken</h2>
                {% endblock %}
            </div>
        </header>
        <div class="content">
            {% block content %}
            We have a bruh moment, nobody should be seeing this.
            {% endblock %}
        </div>
    </body>
</html>

tracken/templates/tracken/edit-goal.html
{% extends 'tracken/base.html' %}
{% block title %}Edit Goal{% endblock %}
{% block header %}
<h2>Edit Goal</h2>
{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div>
        My goal is to complete
        {{ form.hours_goal }}
        hours of work.
    </div>
    <br>
    <div>
        <button type="submit">Update goal</button>
    </div>
</form>
{% endblock %}

tracken/templates/tracken/entry.html
{% extends 'tracken/base.html' %}
{% block title %}Log Entry{% endblock %}
{% block header %}
<h1>Entry logged</h1>
{% endblock %}
{% block content %}
<table>
    <tr>
        <td>Goal:</td>
        <td>{{ entry.goal }}</td>
    </tr>
    <tr>
        <td>Accomplishments:</td>
        <td>{{ entry.accomplishments }}</td>
    </tr>
    <tr>
        <td>Hours:</td>
        <td>{{ entry.time_spent }}</td>
    </tr>
    <tr>
        <td>Time:</td>
        <td>{{ entry.work_date }}</td>
</table>
{% endblock %}

tracken/templates/tracken/home.html
{% extends 'tracken/base.html' %}
{% block title %}Home{% endblock %}
{% block header %}
<h1>
    Tracken
</h1>
<h2>
    Your IDS Tracker
</h2>
{% endblock %}

{% block content %}
This is for Thomas's IDS presentation.
{% endblock %}

tracken/templates/tracken/new-entry.html
{% extends 'tracken/base.html' %}
{% block title %}New Entry{% endblock %}
{% block header %}
<h2>Log a new entry</h2>
{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div>
        <p class="labelPadding">{{ field.label_tag }}</p>
        <p class="fieldPadding">{{ field }}</p>
    </div>
    {% endfor %}
    <div>
        <button type="submit">Log entry!</button>
    </div>
</form>
{% endblock %}

tracken/templates/tracken/progress.html
{% extends 'tracken/base.html' %}

{% block title %}Progress{% endblock %}
{% block header %}
<h2>Your IDS Progress</h2>
{% endblock %}

{% block content %}
<p>
    <h3>
        <a href="{% url 'tracken:new-entry' year=year %}">
            <button>Log a new entry</button>
        </a>
    </h3>
</p>
<div class="hourStatus">
    <p>{{ hours_spent }} out of {{ hours_goal }} hours logged</p>
    <div>
        <a href="{% url 'tracken:edit-goal' pk=year %}"><button>Edit goal</button></a>
    </div>
</div>

{% if entry_list %}
<ul>
    {% for entry in entry_list %}
    <li>
        <a href="{% url 'tracken:entry' pk=entry.id %}">
            {{ entry.goal }}
            <span class="right">{{ entry.work_date }}</span>
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>You haven't logged any IDS work yet. Get cracking!</p>
{% endif %}
{% endblock %}